version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
