version: '3'
services:
  cockroach-01:
    image: cockroachdb/cockroach:v2.0.5
    restart: always
    command: start --insecure
    ports:
      - "26257:26257"
      - "8000:8080"
    environment:
      COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING: "true"

  cockroach-02:
    image: cockroachdb/cockroach:v2.0.5
    restart: always
    command: start --insecure --join=cockroach-01
    environment:
      COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING: "true"

  cockroach-03:
    image: cockroachdb/cockroach:v2.0.5
    restart: always
    command: start --insecure --join=cockroach-01
    environment:
      COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING: "true"

  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
