version: 2

jobs:
  build:
    working_directory: /go/src/github.com/utilitywarehouse/cockroach-backup
    docker:
      - image: circleci/golang:1.11
        environment:
          NAMESPACE: partner
          SERVICE: cockroach-backup
          UW_DOCKER_REGISTRY: registry.uw.systems
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: make install
      - run: make test
      - run:
          name: docker build
          command: >
            GIT_SUMMARY=$(git describe --tags --dirty --always) && GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) &&
            docker build --build-arg GIT_SUMMARY=$GIT_SUMMARY --build-arg GIT_BRANCH=$GIT_BRANCH -t $UW_DOCKER_REGISTRY/$NAMESPACE/$SERVICE:$CIRCLE_SHA1 .
      - run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD $UW_DOCKER_REGISTRY
      - run:
          name: docker tag
          command: >
            if [ $CIRCLE_BRANCH = 'master' ]; then
              docker tag $UW_DOCKER_REGISTRY/$NAMESPACE/$SERVICE:$CIRCLE_SHA1 $UW_DOCKER_REGISTRY/$NAMESPACE/$SERVICE:latest;
            else
              docker tag $UW_DOCKER_REGISTRY/$NAMESPACE/$SERVICE:$CIRCLE_SHA1 $UW_DOCKER_REGISTRY/$NAMESPACE/$SERVICE:$CIRCLE_BRANCH;
            fi
      - run: docker push $UW_DOCKER_REGISTRY/$NAMESPACE/$SERVICE

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: org-global
