name: build

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build container image
        run: make ci-docker-build
        env:
          SERVICE: sql-backup
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_UW_SYSTEMS_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_UW_SYSTEMS_PASSWORD }}